CREATE TABLE IF NOT EXISTS produtos (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  preco NUMERIC(10, 2) NOT NULL CHECK (preco >= 0),
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
